create table country
(
    id         int8 generated by default as identity,
    name       varchar(255) not null,
    alpha2Code varchar(2),
    alpha3Code varchar(3),
    capital    varchar(255),
    population int8,
    area       float8,
    flag       varchar(255),
    primary key (id)
);
