create table digital_nomad (
   id int8 generated by default as identity,
   email varchar(50) not null,
   first_name varchar(50),
   last_name varchar(50),
   nickname varchar(20) not null,
   gender int4,
   location_id int8,
   primary key (id)
);