create table continent
(
    id         int8 generated by default as identity,
    name       varchar(255) not null,
    area       float8,
    primary key (id)
);

alter table if exists continent add constraint UK_continent_name unique (name);
