create table app_user (
   id int8 generated by default as identity,
   username varchar(30),
   password varchar(50),
   account_non_expired boolean,
   account_non_locked boolean,
   credentials_non_expired boolean,
   enabled boolean,
   email varchar(50) not null,
   first_name varchar(50),
   last_name varchar(50),
   nickname varchar(20) not null,
   gender int4,
   location_id int8,
   primary key (id)
);

alter table if exists app_user add constraint UK_app_user_username unique (username);
alter table if exists app_user add constraint UK_app_user_email unique (email);
